### PR TITLE
Bundle Update on 2015-11-19

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [bullet](http://github.com/flyerhzm/bullet), [4.14.7...4.14.10](https://github.com/flyerhzm/bullet/compare/4.14.7...4.14.10) ([CHANGELOG](https://github.com/flyerhzm/bullet/blob/master/CHANGELOG.md))
- Updated: [byebug](http://github.com/deivid-rodriguez/byebug), [6.0.2...8.2.0](https://github.com/deivid-rodriguez/byebug/compare/v6.0.2...v8.2.0) ([CHANGELOG](https://github.com/deivid-rodriguez/byebug/blob/master/CHANGELOG.md))
- Updated: [celluloid](https://github.com/celluloid/celluloid), [0.17.1.2...0.17.2](https://github.com/celluloid/celluloid/compare/v0.17.1.2...v0.17.2) ([CHANGELOG](https://github.com/celluloid/celluloid/blob/master/CHANGES.md))
- Updated: [celluloid-essentials](https://github.com/celluloid/celluloid-essentials), [0.20.2.1...0.20.5](https://github.com/celluloid/celluloid-essentials/compare/v0.20.2.1...v0.20.5) ([CHANGELOG](https://github.com/celluloid/celluloid-essentials/blob/master/CHANGES.md))
- Updated: [celluloid-extras](https://github.com/celluloid/celluloid-extras), [0.20.1...0.20.5](https://github.com/celluloid/celluloid-extras/compare/v0.20.1...v0.20.5) ([CHANGELOG](https://github.com/celluloid/celluloid-extras/blob/master/CHANGES.md))
- Updated: [celluloid-fsm](https://github.com/celluloid/celluloid-fsm), [0.20.1...0.20.5](https://github.com/celluloid/celluloid-fsm/compare/v0.20.1...v0.20.5) ([CHANGELOG](https://github.com/celluloid/celluloid-fsm/blob/master/CHANGES.md))
- Updated: [celluloid-pool](http://github.com/celluloid/celluloid-pool), [0.20.1...0.20.5](https://github.com/celluloid/celluloid-pool/compare/v0.20.1...v0.20.5) ([CHANGELOG](https://github.com/celluloid/celluloid-pool/blob/master/CHANGES.md))
- Updated: [celluloid-supervision](https://github.com/celluloid/celluloid-supervision), [0.20.1.1...0.20.5](https://github.com/celluloid/celluloid-supervision/compare/v0.20.1.1...v0.20.5) ([CHANGELOG](https://github.com/celluloid/celluloid-supervision/blob/master/CHANGES.md))
- Updated: [childprocess](http://github.com/jarib/childprocess), [0.5.6...0.5.8](https://github.com/jarib/childprocess/compare/v0.5.6...v0.5.8)
- Updated: coffee-script-source, 1.9.1.1...1.10.0
- Updated: [minitest](https://github.com/seattlerb/minitest), 5.8.1...5.8.3 ([CHANGELOG](https://github.com/seattlerb/minitest/blob/master/History.rdoc))
- Updated: [netrc](https://github.com/geemus/netrc), [0.10.3...0.11.0](https://github.com/geemus/netrc/compare/v0.10.3...v0.11.0)
- Updated: [newrelic_rpm](http://github.com/newrelic/rpm), [3.13.2.302...3.14.0.305](https://github.com/newrelic/rpm/compare/3.13.2.302...3.14.0.305) ([CHANGELOG](https://github.com/newrelic/rpm/blob/master/CHANGELOG))
- Updated: [nokogiri](https://github.com/sparklemotion/nokogiri), [1.6.6.2...1.6.6.3](https://github.com/sparklemotion/nokogiri/compare/v1.6.6.2...v1.6.6.3) ([CHANGELOG](https://github.com/sparklemotion/nokogiri/blob/master/CHANGELOG.ja.rdoc))
- Updated: [pg](https://bitbucket.org/ged/ruby-pg), [0.18.3...0.18.4](https://bitbucket.org/ged/ruby-pg/branches/compare/v0.18.4%0Dv0.18.3) ([CHANGELOG](https://github.com/ged/ruby-pg/blob/master/History.rdoc))
- Updated: [redis](https://github.com/redis/redis-rb), [3.2.1...3.2.2](https://github.com/redis/redis-rb/compare/v3.2.1...v3.2.2) ([CHANGELOG](https://github.com/redis/redis-rb/blob/master/CHANGELOG.md))
- Updated: [redis-activesupport](https://github.com/redis-store/redis-activesupport), [4.1.1...4.1.5](https://github.com/redis-store/redis-activesupport/compare/v4.1.1...v4.1.5)
- Updated: [redis-store](https://github.com/jodosha/redis-store), [1.1.6...1.1.7](https://github.com/jodosha/redis-store/compare/v1.1.6...v1.1.7) ([CHANGELOG](https://github.com/redis-store/redis-store/blob/master/CHANGELOG))
- Updated: [sass](https://github.com/sass/sass), [3.4.18...3.4.19](https://github.com/sass/sass/compare/3.4.18...3.4.19)
- Updated: [spring](https://github.com/rails/spring), [1.4.0...1.4.4](https://github.com/rails/spring/compare/v1.4.0...v1.4.4) ([CHANGELOG](https://github.com/rails/spring/blob/master/CHANGELOG.md))
- Updated: [sprockets](https://github.com/rails/sprockets), [3.3.5...3.4.0](https://github.com/rails/sprockets/compare/v3.3.5...v3.4.0) ([CHANGELOG](https://github.com/rails/sprockets/blob/master/CHANGELOG.md))
- Removed: [dotenv](https://github.com/bkeepers/dotenv), [2.0.2](https://github.com/bkeepers/dotenv/tree/v2.0.2)
- Removed: [nenv](https://github.com/e2/nenv), [0.2.0](https://github.com/e2/nenv/tree/v0.2.0)
- Removed: [rspec-logsplit](https://github.com/abstractive/rspec-logsplit), [0.1.3](https://github.com/abstractive/rspec-logsplit/tree/v0.1.3)

--

Brought to you by [deppbot](https://www.deppbot.com) - Automated Dependency Updates
18 Pull Requests sent and 19 minutes, and 35 seconds saved so far.

<sub>Feedback or Bug Reports? Please let us know via [Email](mailto:ask@deppbot.com) or [GitHub Issues](https://github.com/deppbot/feedback).</sub>

### CODE REVIEW

**Comment by winston** [comment]
Looking at Travis CI, these two specs failed:

```
  1) Failure:
ViewBenchmarkGraphsTest#test_User_should_not_be_able_to_view_releases_memory_benchmark_graph_if_it_does_not_exist [/home/travis/build/ruby-bench/ruby-bench-web/test/acceptance/view_benchmark_graphs_test.rb:206]:
Failed assertion, no message given.
  2) Error:
ViewBenchmarkGraphsTest#test_User_should_be_able_to_view_releases_benchmark_graphs:
Capybara::ElementNotFound: Unable to find css ".release-chart .highcharts-container .highcharts-yaxis-title"
    test/acceptance/view_benchmark_graphs_test.rb:157:in `block in <class:ViewBenchmarkGraphsTest>'
```

So I tried to run these two specs locally. I didn't get the same failure though. Instead I got the same error when I ran both tests:

```
NoMethodError: undefined method `environment' for #<BenchmarkRun::ActiveRecord_Relation:0x007fa41cd32328>
    app/controllers/repos_controller.rb:91:in `block (2 levels) in show_releases'
    app/services/chart_builder.rb:12:in `block in build_columns'
    app/services/chart_builder.rb:10:in `each'
    app/services/chart_builder.rb:10:in `build_columns'
    app/controllers/repos_controller.rb:90:in `block in show_releases'
    app/controllers/repos_controller.rb:76:in `map'
    app/controllers/repos_controller.rb:76:in `show_releases'
```

Digging into it.. On https://github.com/ruby-bench/ruby-bench-web/blob/master/app/controllers/repos_controller.rb#L90:

```
columns = ChartBuilder.new(benchmark_runs).build_columns do |benchmark_run|
```

The `benchmark_runs` variable seems to contain an array as such:

```
[Instance 1 of BenchMarkRun, <ActiveRecord::Relation: Instance 2 of BenchMarkRun, Instance 3 of BenchMarkRun>]
```

Which is a mix of BenchMarkRun and Arel.. which caused the error above.

If I do a `flatten` like so:

```
benchmark_runs = benchmark_runs.flatten
```

before line 90, then the specs work. But is this the correct fix?

**Comment by tgxworld** [comment]
Fixed in https://github.com/ruby-bench/ruby-bench-web/commit/bad60258a15ae17f2b3a998d1fb7bb2f382b5f72. Not sure why using scopes was causing it to fail though.

**Comment by winston** [comment]
@tgxworld Ah.. The reason is because you are using `.first` in your scope. When it can't find the records, it will then do a `select *` instead.

So.. Scopes should be chainable and so you shouldn't be using `.first` in it. 

Using `limit(1)` is more accurate in this case, but it will still give you another error to fix (it still appended an empty rel into the `benchmark_runs` array).

Ref: https://github.com/rails/rails/issues/13647

**Comment by tgxworld** [comment]
Ahh ic I didn't know about that xD. Thanks for diving into it!

**Comment by winston** [comment]
:+1:

**Pull request closed without merging**
