### PR TITLE
Add organizations url with organizations list to navbar in page header

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by tgxworld** [comment]
@davydovanton  Thanks for the PR! Let me put this on hold first. We're planning to do a redesign of the flow so this might change. :yellow_heart:

**Comment by davydovanton** [comment]
@tgxworld of course. If you want I can help you with this :eyes:

**Comment by davydovanton** [comment]
@tgxworld I think we can close this PR, what do you think? :smiley:

**Comment by tgxworld** [comment]
Yup! Thanks for the work though! :yellow_heart:

**Comment by davydovanton** [comment]
@tgxworld thanks you too :blush:

**Pull request closed without merging**
