### PR TITLE
Bundle Update on 2015-09-18

### PR DESCRIPTION
**Pull request by deppbot**
**Updated RubyGems:**

- Updated: [minitest-stub-const](https://github.com/adammck/minitest-stub-const) [0.4...0.5](https://github.com/adammck/minitest-stub-const/compare/v0.4...v0.5)

--

Brought to you by [deppbot](https://www.deppbot.com).

### CODE REVIEW

**Comment by JuanitoFatas** [comment]
Master already [upgraded to minitest-stub-const v0.5](https://github.com/ruby-bench/ruby-bench-web/blob/master/Gemfile.lock#L167), close this one?

**Comment by tgxworld** [comment]
haha ok :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by tgxworld** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by JuanitoFatas** [comment]
Thanks! @tgxworld 

Last time I met tenderlove, he asked what is tgx, I told him it is your name initials. :grimacing:

**Pull request closed without merging**
